### ISSUE TITLE
Select2

### ISSUE THREAD

**Issue by bebepeng** [pivotal-cf/pivotal-ui#148]
Our pre-PUI pages use [select2](https://select2.github.io/) heavily for searchable select boxes. After moving to PUI, we are finding it to be very difficult to style the faux-select input to look consistent with normal PUI form inputs. Not using select2 would be a bit of a downgrade in functionality. Would it be possible for you guys to help us out with styling? Or would it be possible for you to provide a searchable select input in PUI?

Thanks!

cc: @pivotal-plech  @matt-royal

**Comment by nicw** [comment]
@bebepeng we've just realized a new version that may help with some of your styling. Can you try with the 2.0 version and let us know if this still an issue? Thanks!

**Comment by bebepeng** [comment]
Hi @nicw!  I'm not on Pivnet anymore, but @mdelillo is!

**Comment by mdelillo** [comment]
I also rolled off Pivnet, @toothrot is the new anchor.

**Comment by toothrot** [comment]
I'll check this out and will get back to you!

**Comment by toothrot** [comment]
It looks like we still need to do a significant amount of styling on our side to get it to fit in with PUI. 

It'd be nice if PUI had a component built in for some of this functionality. In the meantime, it looks like we'll have to keep the current blob of custom styles to keep it looking consistent.

**Comment by nicw** [comment]
@toothrot agreed, and this is something the Pivotal design team has in their backlog to work out. When they've worked out the design, it'll come back here.

**Comment by nicw** [comment]
Alex, the thinking here is that Select2 is a well established library that
lives on because of its support and focused talent. What they offer isn't
our core competence, so we aren't going to offer that.

As the style guide, our goal is to provide the guidelines around look and
feel, and let the teams decide the technology behind the execution. To be
honest, Select2 has always been a beast to customize, and you and your team
would be doing a great service to give them feedback for more intuitive
styling.

Cheers, the PUI team.

**Comment by rdy** [comment]
@nicw don't worry i'm working with pivnet right now and I'll find a way they can use our autocomplete or existing select components.

**Comment by nicw** [comment]
👍🏼
