### ISSUE TITLE
.help-inline is an undocumented class

### ISSUE THREAD

**Issue by DougBlumeyer** [pivotal-cf/pivotal-ui#208]
Can be found in forms.scss. 

It looked like a compliment to .help-block. Instead, it appears to have been pulled in ages ago from Apps Manager and is unrelated. I was hoping it might be just like .help-block except display: inline, but it is also still display: block.

Maybe deprecate, or change to display: inline?

**Comment by nicw** [comment]
@DougBlumeyer good catch, thanks. We took a look and we're going to to deprecate this class.

Here's a little more info from @kennyw12 , any more feedback is appreciated.
----
Bootstrap 3 also deprecates help-inline and recommends users to use help-block. Since help-inline uses "error" colors, it seems like it is trying to accomplish what help-block has-error is doing. The major difference between the two is the padding and capitalization which I think shouldn't be conflated with help-inline and separated out into another class (possibly has-error depending on the use case).
---
