### ISSUE TITLE
Document Variables + Mixins in the Styleguide

### ISSUE THREAD

**Issue by pivotal-plech** [pivotal-cf/pivotal-ui#299]
Is there somewhere where they exist in the documentation today?

Would be nice to have included when building out application specific components. Currently you have to know that they exist on NPM I think...

**Comment by rdy** [comment]
Variables can be included but mixins aren't yet exported in any useable way. We should document the module the variables are in and we should add a new module or reuse the same one for our mixins.

**Comment by atomanyih** [comment]
we document colors on:
http://styleguide.pivotal.io/css_utilities_colors.html

this page is interesting because it tells you to install `pui-css-colors` but it's really documenting the colors available in `pui-css-variables-and-mixins`

For now, I'm going to change the npm line, but we should probably document the actual `pui-css-colors` module somewhere.

this also doesn't document mixins, size variables or any of the numerous other things in `pui-css-variables-and-mixins`

**Comment by atomanyih** [comment]
actually, we just followed nic's instructions from the tracker story

https://github.com/pivotal-cf/pivotal-ui/commit/61a1d814473422271d402dc09cd1e79471073d75
