### ISSUE TITLE
Add componentDidAnimate callbacks

### ISSUE THREAD

**Issue by kayline** [pivotal-cf/pivotal-ui#305]
The Support Portal team needs to scroll after an expander has opened. React has no callbacks for post-CSS-animation, it would be really nice if the PUI components that use CSS animations included callbacks for when the animations are finished. We're hacking it with jQuery right now.

**Comment by atomanyih** [comment]
That sounds like a fab idea!

Sorry for the late response, PUI is working at pretty low bandwidth right now (1 person, ~1 day a week).
It doesn't look like a hard feature to implement, but I'm not sure when I can get to it. In the meantime, pull requests are welcome!

We're trying to have a more bidirectional relationship with teams using PUI; not just because of limited time, but also because it often makes more sense for the people who need the features to implement and throw them back as PRs.

I took a quick look at expanders, and it looks like we could just pass through more properties onto react-bootstrap's expanders... seems like a doable PR if you're up for it

If you have any questions, I'm on the 4th floor at the desks by the elevators

**Comment by charleshansen** [comment]
Expander has `onExited` and `onEntered` callbacks now for closed and opened
