### ISSUE TITLE
Tabs disappear

### ISSUE THREAD

**Issue by kennyw12** [pivotal-cf/pivotal-ui#332]
When switching tabs from mobile view to desktop view or vise versa, the tab pane disappears.

**Comment by atomanyih** [comment]
besides [this issue on react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/issues/557) we haven't been able to reproduce this. 

in fact, if you lose the pane in the above way, switching between mobile/desktop view will actually bring the pane back. this is because the tab component is removed at small sizes and remounted at large sizes.

I can't think of an obvious reason why changing the size would cause the tab content to disappear.
If this is still a thing, it's probably a bug in react bootstrap
