### ISSUE TITLE
Cannot customize classes or properties of PivUI React Modal component header 

### ISSUE THREAD

**Issue by RochesterinNYC** [pivotal-cf/pivotal-ui#340]
The following is an example of our usage of the PUI React Modal component:

![screen shot 2015-12-11 at 9 55 58 am](https://cloud.githubusercontent.com/assets/1504464/11746757/70897f44-9fed-11e5-9b9e-0ec538ab6ea8.png)

We wanted to customize it with things like passing through `.bg-neutral-11` to the modal-header (to make it white) and removing the x button in the top right (something that you can do with the [Bootstrap React Modal](https://react-bootstrap.github.io/components.html#modals-props-modal-header) that the PUI Modal builds on). However, this is not currently possible and we have to circumvent it by adding a top level class to the modal and writing CSS to change `.modal-header`. We don't have this problem with the ModalBody or ModalFooter because we explicitly pass those in as children. It'd be nice to be able to pass through classNames and properties to the header.

- James && Marc (mmagruder@pivotal.io)

**Comment by charleshansen** [comment]
This is all reasonable behavior we should support. I assume you are using PUI 2. This is fixed in the current PUI. We don't have enough developer bandwidth to fix this in PUI 2 right now, but would take a PR.

For reference PUI 2 Modals do not use React Bootstrap. PUI 3 Modals are a thin wrapper around React Bootstrap Modals and get all of this behavior for free.
