### ISSUE TITLE
When the bar is at a low percentage,  it is hard to read the number due to the light background

### ISSUE THREAD

**Issue by helenkchung** [pivotal-cf/pivotal-ui#354]
Would it be possible to change the percentage number to be color neutral-3(hex:686868) that changes to white when the bar is red?

**Comment by pivotal-plech** [comment]
@helenkchung

I agree that the contrast is really poor when the percentage is low, but it's actually equally as bad when it's over 8-9% full:

![image](https://cloud.githubusercontent.com/assets/4721717/12728368/860f444a-c8ef-11e5-93a0-f52109a83809.png)

@edahl9 do you have an opinion for how this might be designed to accommodate for all states?

**Comment by edahl9** [comment]
When I put the font color to neutral 3 (#686868) I think it looks acceptable. If it's still an issue you can throw it down to neutral 2 (#424242). It's tertiary information because the straight MB count and visual representation is more important. I believe I sat with August when we made it so that when the bg turns to red at the 90% mark the text color is supposed to go to white. Either way that percentage doesn't feel important enough to bust out of there. The only issue I have with it now is that the percentage doesn't look properly middle aligned. @pivotal-plech

**Comment by paulfarino** [comment]
@elliotdahl @pivotal-plech 
For the readability issue you could also use a function to determine the text color. When the rules to determine the background color changes—you'll still maintain readability.

An example scenario:
**Currently:** If the progress bar is ≥ 90% the background turns red and the text turns white.
In the future, if a rule is added such as: When the progress bar is <10%, the bar background should turn red. Readability will suffer.

---
I created a [simple example](http://codepen.io/paulfarino/pen/ORVdrR) to show how that function might look.

**Comment by elliotdahl** [comment]
This is fixed.
