### ISSUE TITLE
Tooltips w/ Overlay Tigger not working in React 15

### ISSUE THREAD

**Issue by Plummat** [pivotal-cf/pivotal-ui#385]
Haven't had time to investigate, but it causes an invariant violation:

Error: traverseParentPath(...): Cannot traverse from and to the same ID, ``.

**Comment by charleshansen** [comment]
Pivotal UI is currently untested in React 15. There is a peer dependency on React 14 in our package jsons, so it is possible you are accidentally loading two versions of React.

**Comment by Plummat** [comment]
Not sure I had two versions loaded, but will double check when i get a chance to hop back on that branch.  ETA on 15 release?

**Comment by charleshansen** [comment]
It shouldn't be too hard to upgrade to 15, but we don't have any specific plans for it. It isn't super high priority since there are no important features in 15 that aren't in 14 unless you count improved SVG support. Now that at least one person has been trying it, it will probably happen in a week or two.

**Comment by charleshansen** [comment]
It turns out it was a bug in Overlay Triggers specifically. It should be fixed in the most recent commit, and PUI will work in both 14 and 15. We should publish it soon.

**Comment by charleshansen** [comment]
Fixed in 5.0
