### ISSUE TITLE
Support LESS format

### ISSUE THREAD

**Issue by BoykoAlex** [pivotal-cf/pivotal-ui#393]
Any chance the frankenstyle's output can be turned into component.less file. This might be possible with vinyl-fs transforms. Same goes for individual components pui-css-... buttons, tabs, bootstrap etc. (I could try and convert these CSS files into LESS in my grunt build, but other apps mey also require LESS)
Also, it'd helpful to get .less format from pui-variables-and-mixins.

**Comment by rdy** [comment]
This can be accomplished by using something like this:
https://www.npmjs.com/package/gulp-less-to-scss

I'm not sure if I'd really recommend doing such a thing. Is there a strong reason why you need to have a less output rather than css? Pivotal-ui is based on bootstrap which is now sass based.

I'd probably recommend just sticking with the css rather than adding additional transformation steps to keep things simple.

One more thing, is that Dr. Frankenstyle is being deprecated in favor of doing things more directly with webpack.

**Comment by BoykoAlex** [comment]
Yesterday i took a look at bootstrap 4 and saw that it is indeed uses SCSS instead of LESS. I suppose we'd be upgrading to SCSS sooner or later and this makes the issue not applicable :-)
Thanks for the info :-)
