### ISSUE TITLE
cf push

### ISSUE THREAD

**Issue by yackitotreeville** [pivotal-cf/pivotal-ui#396]
Hi, I am currently experimenting  with pivotal-ui. As recommended I am using webpack and webpack-dev-server. When I am doing cf push, I am getting error with webpack-dev-server. Is PCF compatible with webpack?? So my issue is more related to cf push when using webpack-dev-server.

**Comment by charleshansen** [comment]
What project are you trying to cf push? If you are based on react-starter, there is a gulp deploy task to do this for you. In that example, we actually compile all of the assets and server everything as a static app. 

If you want a server running on cf, I suggest you use express instead of webpack-dev-server. We used to use webpack-dev-server for development only, I've never tried pushing it to cf. We now use webpack-dev-middleware embedded in an express server instead of webpack-dev-server. webpack-dev-middleware is not used when we push to cf.

Hope that helps, let me know if you need more info.

**Comment by rdy** [comment]
You should not push webpack-dev-server to production, it is not meant to run as a production server:

Refer to the first line of their README.
https://github.com/webpack/webpack-dev-server

You should compile your assets to static files and serve those files up in your project. There are a lot of reasons not to use webpack-dev-server in your application on cf. Charles describes a method to serve those files generated by webpack with an express server but you could always use nginx or any web server, really.
