### ISSUE TITLE
Provide a Sass Release of All Components

### ISSUE THREAD

**Issue by ghillert** [pivotal-cf/pivotal-ui#440]
Over at the _Spring Cloud Data Flow_ team (Pivotal) we are investigating to migrate our code-base to Angular2 using PUI and we look at using Sass for styling. 

Right now it looks like only `pui-css-variables-and-mixins` are available as Sass files via NPM:

- mixins.scss
- pui-variables.scss

```
npm install --save pui-css-variables-and-mixins
```

Since all components are defined using Sass, it would be awesome if I could install the entire PUI via NPM and have all Sass components available.

**Comment by charleshansen** [comment]
Welcome to Pivotal UI. Thanks for checking in. We haven't had time for parts of the documentation in a little bit, so I'm happy if you fire off github issues as soon as something doesn't make sense.

What do you need the sass for? All of the components css is already exposed directly for you to use (I'm happy to give more info if you are  having difficulty using the component css, it is tricky if you aren't using pui-react-tools).  We use very low specificity css rules so you can override things easily. The sass variables are mostly exposed so that you can create your own components with the Pivotal colors. 

You should also seriously consider using React instead of Angular2:

 - From the Pivotal UI perspective, there is a lot of behavior you need JavaScript for and we have chosen to provide that behavior in React Components. The css components will still provide a lot of value, but things like dropdowns and modals will be annoying without the React components.

- Speaking as an individual developer (feel free to ignore this part), React just leads to more maintainable code and faster feature development than Angular does. Also, working with React teaches you JavaScript and functional programming, skills that are useful anywhere. Working with Angular just teaches you the Angular API, which is kind of odd and not applicable anywhere else. I assume your team has reasons for using Angular, but I wanted to make you double check you want to go down that road. The React path is pretty great.

**Comment by jadekler** [comment]
@ghillert Is this topic still something your team is looking for?

**Comment by ghillert** [comment]
@jadekler Yes - Would love to. The ability to use the Sass files via NPM dependencies would be quite useful.

**Comment by jberney** [comment]
@ghillert If this helps, here is a CDN version of PUI: http://d2bsvk2etkq8vr.cloudfront.net/pui-css/pui-components-8.3.1.css

Do you specifically need the uncompiled SASS? If so, we'll check with our PM about getting this work prioritized.

**Comment by ghillert** [comment]
@jberney Yes, having the ability to consume the uncompiled Sass - that would be best. Does not have to be on a per component basis. If the main-all-encompassing-distribution on NPM could contain all relevant Sass files, that would work for us. That way we have the most flexibility in customizing variables to our needs.

**Comment by charleshansen** [comment]
@ghillert I'm still trying to understand the use case. Is the issue that you want to use Pivotal UI components for general look and feel, but you want to use the Spring color palette? We might be able to add some functionality for you to change some sass variables and get a custom (unpublished) css distribution.

For context, I'm not sure how we could easily distribute the sass in a useable way and am trying to find the simplest solution that would work for you.

**Comment by charleshansen** [comment]
@ghillert It might be easier to discuss your use case in person, or at least over a hangout. Can you get in touch with us on the Pivotal UI slack channel to set something up?

**Comment by sjolicoeur** [comment]
@ghillert @charleshansen, closing this as the sass can be consumed from the repo (git cloned into your project).
