### ISSUE TITLE
Add more examples for uses of color

### ISSUE THREAD

**Issue by ColbySato** [pivotal-cf/pivotal-ui#471]
As someone new to PUI, I was not sure exactly how each color range was used, so some examples of good use of it would be helpful for keeping consistency. 

ex. dark-1 is used for headers as you can see on the Apps Manager Page
neutral-1 is used for body text as you can see on the BAM Billing Statement page. 

https://styleguide.cfapps.io/css_utilities_colors.html

**Comment by charleshansen** [comment]
This sounds like a great idea. The styleguide is currently more focused on developers and tends not to answer this kinda of question very well. I believe this will be fixed in the styleguide redesign that is under work right now. I'll try to backport the improved documentation when it is created by the design team.

**Comment by elliotdahl** [comment]
Great idea. Let's sync up @ColbySato about how design can contribute to this.
