### ISSUE TITLE
pui-css-backgrounds doesn't install with "images" directory

### ISSUE THREAD

**Issue by ftripier** [pivotal-cf/pivotal-ui#493]
Ubuntu: v16.0.4
Yarn: v0.2.3
Node: v7.7.3
PUI: v8.0.4

In this environment, running yarn install outputs a pui-css-backgrounds directory in node_modules without an "images" directory.

**Comment by charleshansen** [comment]
I don't have a linux machine handy right now, but I was able to yarn install with yarn v0.21.3. I have a folder at `node_modules/pui-css-backgrounds/images` Maybe you need to upgrade your yarn? Let me know if that doesn't fix it.

There have been bugs in the past where the `npm publish` api request partially fails and does not publish all of the assets, but it does not look like this is the case here.

Also, I didn't think anyone used pui-css-backgrounds and was considering deprecating it. Do you have a use case for it?

**Comment by ftripier** [comment]
Oh sorry, my yarn is actually at 0.21.3. Everything works perfectly on mac, but linux is misbehaving. My use case is just that I'm using pui-css-all, but I've actually been using the backgrounds just because I'm a design ignoramus and wanted to use a neutral color scheme externally validated by someone with more expertise.

**Comment by charleshansen** [comment]
Oh weird, two more questions for you:

Does it work with npm instead of yarn? 
Does it work for other versions of PUI (like 8.0.3 or 7.5.5)?

Also, for what it is worth, it sounds like you aren't actually using `pui-css-backgrounds`, those are very specific and largely useless (http://styleguide.pivotal.io/css_base_backgrounds.html). It sounds like you are using `pui-css-colors`. That is the package that gives you classes like `bg-neutral-10`, etc.

**Comment by charleshansen** [comment]
Is this still an issue?

**Comment by charleshansen** [comment]
closed for inactivity
