### ISSUE TITLE
pui-react-modals: Prevent Click-out From Closing Modal?

### ISSUE THREAD

**Issue by mdreyer** [pivotal-cf/pivotal-ui#527]
**Steps to Reproduce**
1) open modal
2) click on modal backdrop or somewhere outside of modal

**Expected**
modal should remain open until the close button is clicked

**Result**
modal closes

does pui-react-modals provide any way of accomplishing this behavior? or will I have to implement this myself?

thanks!

**Comment by charleshansen** [comment]
Modals somewhat support this behavior. You can pass in an `onHide` prop as a callback. If `onHide` is called with a click event that comes from the modal backdrop, you can just ignore it. Note that for a stateless modal, you are the one in charge of when the modal closes, not Pivotal UI code.

Just to be clear, you want the modal backdrop to still exist and you want it to still block clicks to things behind it. You just don't want the modal to close when someone clicks on it? We could in theory support a `closeOnScrimClick` boolean that will prevent `onHide` from being called when you click on the backdrop, but I don't know if this is much better than just filtering events from `onHide`.

Also just to be clear, you can close a modal by hitting the escape key. Not sure if you want this behavior. The way our code is written makes it hard to filter on this use case because we are not passing the keyboard event through here. This could be easily added if you want it.

**Comment by sjolicoeur** [comment]
To clarify, the `onHide` prop should be passed to `BaseModal` and should look like this:
```
onHide={(e) => {
                       if (e.currentTarget.classList.includes('modal-backdrop')) return
                       this.setState({modalOpen: false})
                   }}>
```

This code does happen to work, but only accidentally. We do not always pass the event when calling `onHide`, it is currently only passed when you click the close button. Looking up `e.currentTarget` will cause a runtime error, and then `this.setState` won't be called. We should fix this in PUI.

**Comment by reid47** [comment]
We have a story tracking this feature. It will be in Pivotal UI version 9:
https://www.pivotaltracker.com/story/show/150454266
