### ISSUE TITLE
Update to Bootstrap 4

### ISSUE THREAD

**Issue by ghillert** [pivotal-cf/pivotal-ui#528]
Looks like Bootstrap 4 is more or less feature-complete now: 

https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

Any plans to migrate to Bootstrap 4?

**Comment by charleshansen** [comment]
There are no plans to upgrade Bootstrap, since I would rather spend that energy on removing it. Bootstrap css has a lot of unexpected side effects I would rather not force our users to deal with.

The current plan is to slowly replace bootstrap css in Pivotal UI when we update components. Ideally Bootstrap will be gone after a few more major versions, but it has proven extremely difficult to remove.
