### ISSUE TITLE
React: Remove deprecated propTypes usage to support React 15.5

### ISSUE THREAD

**Issue by kevynb** [pivotal-cf/pivotal-ui#535]
Hello,

I'm getting the following warning when using the `<OverlayTrigger>` component:

```
lowPriorityWarning.js?d93c:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

It seems to be because this component uses the [`react-tether`](https://github.com/souporserious/react-tether) library in version `0.5.2` that still uses `react.Proptypes`. This behaviour was fixed in version 0.5.7. 

Do you think an upgrade is possible?

Thanks!

**Comment by sjolicoeur** [comment]
@kevynb In which version of pivotal-ui are you seeing this issue?

**Comment by kevynb** [comment]
I'm using npm package "pui-react-tooltip": "^8.3.3" which seems to be the latest version available on npm.

**Comment by sjolicoeur** [comment]
@kevynb  I see! Since version 9 we stopped publishing the individual components in a stand-alone manner, and are publishing them all under [Pivotal-UI](https://www.npmjs.com/package/pivotal-ui) to get individual components now a simple import of the specific component is necessary. it also makes it easier for `package.json` maintenance

```
import {OverlayTrigger} from 'pivotal-ui/react/overlay-trigger';
```

Would you be able to upgrade to v9 at the very least? Or v10 would be the latest?

**Comment by kevynb** [comment]
Hello,

I upgraded to version 9, since it seems I cannot use version 10 until we migrate to React 16.
It's indeed much easier to have them all in one package.

Thanks problem fixed!
