### ISSUE TITLE
Blue loader line animation causes panic attacks

### ISSUE THREAD

**Issue by denniscollective** [pivotal-cf/pivotal-ui#554]
I'm super ADHD and have a hard time maintaining my focus.

The blue loading line is incredibly distracting and I cease being able to accomplish whatever task I was working on when it's up.

Metrics frequently shows the loaders for times  > 1 minute
Health Watch uses it for bosh deployments, so it shows up for hours.

In Health Watch I have to go into the Chrome Inspector and remove the dom node.
In metrics I have to hide the tab and wait several minutes to return.

I was just looking at the docs page for the panels, freaked out, and came here and had to write this issue.

Please come up with a a more subtle animation and/or have firm guidelines around not showing it for more than a second.

I wish I were being hyperbolic with my language but this design is super (unintentionally) hostile towards neuro-atypical people.

**Comment by mingxiao** [comment]
Thanks for filing this issue.

Would it help if we lowered the speed of the animation? Or is the presence of it distracting in and of itself?

**Comment by reid47** [comment]
Hi @denniscollective, sorry for the delay in responding. In the v16 release, we changed the loading animation on the `Panel` component to (hopefully) be less jarring. It is now gray instead of blue, and the speed was lowered considerably. If you get a chance, please check out the new animation here:

https://styleguide.pivotal.io/panels

I'm going to close this issue for now, but feel free to reopen it if you take a look at the new animation and still feel this way Thank you for helping us improve Pivotal UI!
