### ISSUE TITLE
.container has fixed width at different screen sizes that lose a lot of real estate

### ISSUE THREAD

**Issue by rheaton** [pivotal-cf/pivotal-ui#559]
## What version of Pivotal UI are you using?
14.0.0 (was seen in 13.x as well)

## What browser and version are you using?
Tested in Chrome, FF, and IE11.

## What behavior are you seeing?
On a smaller screen, there is a lot of lost real-estate. Screen size was < 1000 px wide. Play around in that area and you can see the lost real estate.

## What do you expect to see?
I'm not sure if we were not using container as expected (it was the container generated by using a Pane), but it had a max width at very large screens as well. 

Perhaps there need to be more max-widths added? Maybe this is address in 1.15 :)

**Comment by reid47** [comment]
Hi @rheaton, we are taking a look at the Pane component and it hasn't been updated in a long time. We are not sure what the goal of the Pane component was, since it's quite old and we aren't using it on Apps Manager. Could you tell us a little more about what you're trying to achieve with the Pane?

For now, it seems like it would be easier to not use our Pane, and to implement what you need with a plain old `div` and some CSS. We can help if needed, and maybe this could make its way back into PUI.

**Comment by reid47** [comment]
@rheaton Is this still a problem for your team? 

We have deprecated the `Pane` component (removed it from the styleguide) with the intention of deleting it entirely in a future major release. 

If your team is still having trouble, how can we help? And if not, do you mind if we close this issue?

**Comment by rheaton** [comment]
I'm on longer on the team experiencing this issue. Please reach out to @ssapra

**Comment by ssapra** [comment]
Hi @reid47, we did end up moving away from the `Pane` component and rely on the plain old `div`. Thanks for following up.
