### ISSUE TITLE
Prop name `id` in checkbox causes duplicates

### ISSUE THREAD

**Issue by majidmade** [pivotal-cf/pivotal-ui#565]
## What version of Pivotal UI are you using?
`^16.1.0`

## What browser and version are you using?
Chrome 68.0.3440.84

## What behavior are you seeing?
The checkbox component has a prop named `id` that is passed down to the inner `input` child. This is working properly, but it appears that React is also using the same `id` in the virtual dom for the `Checkbox` itself, resulting in duplicate ids in React DevTools and enzyme tests (but *not* the actual DOM):
```jsx
<Checkbox checked={true} id={`my-id`}>
      {statusText}
</Checkbox>
```
React DevTools:
![screen shot 2018-08-14 at 11 10 23 am](https://user-images.githubusercontent.com/19802056/44106788-c66d6250-9fb2-11e8-8dcc-706b958eb017.png)

Enzyme:
![screen shot 2018-08-14 at 11 07 34 am](https://user-images.githubusercontent.com/19802056/44106683-8f00037c-9fb2-11e8-8199-62b7c6519c23.png)

## What do you expect to see?
We can get around this by selecting `input#my-id` specifically, but generally speaking it would be preferable to mount this component without duplicated IDs.

/cc @johannasmith

**Comment by reid47** [comment]
Hi @majidmade, I can see what you're talking about in the React DevTools, but it seems to me that this is the way this should work. 

I would expect that when a component takes an `id` and wants to put it on an input field, it would appear in the virtual DOM both in the place where the user put it (on the `Checkbox`, in this case) and in the place where it gets passed (on the `input`). 

I definitely agree that duplicate `id`s in the real DOM would be a problem, but it seems like this is only causing issues because Enzyme is querying the rendered element tree (the virtual DOM) rather than the real DOM. And it seems like duplicate `id`s would be expected in the virtual DOM in this case. Your solution (using `input#my-id`) seems to me like the right thing to do.

Put another way, I'm not sure how we could fix this problem within our `Checkbox` component. I don't know how we could "remove" the `id` prop from the `Checkbox` and still pass it to the `input`.

Please let me know if there's something I'm missing here!

**Comment by majidmade** [comment]
Thanks @reid47 ! That makes sense; we didn't have strong feelings about this, just figured we'd bring it up for review.
