### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by adidner** [pivotal-cf/pivotal-ui#619]
On this page (https://styleguide.pivotal.io/concepts/8-point-grid/) under the header "Grid & FlexCol components" the "grid page" link returns a 404

**Comment by sweinstein22** [comment]
Hi @adidner, thanks for bringing this to our attention! The issue has been fixed with this commit: https://github.com/pivotal-cf/pivotal-ui/commit/7e2031bfb0a7f678e6db5d602f74579b4edfbf3e. (Note that you may need to use a hard refresh if the page is still cached in your browser to see the change take affect.) 

Please let us know if you are still experiencing this issue, or if any others come to light.
