### ISSUE TITLE
How does Jasmine Dom Matchers work for Jest

### ISSUE THREAD

**Issue by iamdriz** [pivotal-cf/pivotal-ui#638]
I noticed in your Jest specs that you're using Jasmine Dom Matchers: https://github.com/pivotal-cf/pivotal-ui/blob/master/package.json#L46

And this is imported in the jest-setup file: https://github.com/pivotal-cf/pivotal-ui/blob/master/spec/support/jest-setup.js#L3

However I'm struggling to see how this works with Jest? as from what I can see inside the code for the DOM matchers, it just extends the jasmine assertions and Jasmine itself isn't imported as part of the test framework... how does it hook into Jest?

**Comment by reid47** [comment]
Hi @iamdriz, thanks for the question. We are able to do this because Jest uses Jasmine under the hood as its test runner. Jasmine globals are still exposed in Jest tests, though this is undocumented and unsupported. But we relied on this to make the migration from Jasmine to Jest easier.

This link is related:
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-jasmine-globals.md

**Comment by sweinstein22** [comment]
I'm going to close this issue as there hasn't been any new activity in a while. Feel free to reopen if we haven't addressed your question.
